#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

try:
    import gerber_writer  # type: ignore
except ModuleNotFoundError:
    gerber_writer = None


def write_stub_file(path: Path, lines: list[str]) -> None:
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def mm_to_coord(value_mm: float) -> str:
    # With FSLAX24, coordinates are encoded with 4 decimal places in mm.
    return f"{int(round(value_mm * 10000)):07d}"


def to_board_local(x: float, y: float, origin_x: float, origin_y: float) -> tuple[float, float]:
    return (x - origin_x, y - origin_y)


def append_trace(
    gerber_lines: list[str],
    points: list[dict],
    aperture: str,
    origin_x: float,
    origin_y: float,
) -> None:
    if len(points) < 2:
        return

    start = points[0]
    start_x, start_y = to_board_local(float(start["x"]), float(start["y"]), origin_x, origin_y)
    gerber_lines.append(f"{aperture}*")
    gerber_lines.append(f"X{mm_to_coord(start_x)}Y{mm_to_coord(start_y)}D02*")
    for point in points[1:]:
        px, py = to_board_local(float(point["x"]), float(point["y"]), origin_x, origin_y)
        gerber_lines.append(
            f"X{mm_to_coord(px)}Y{mm_to_coord(py)}D01*"
        )


def append_board_outline(gerber_lines: list[str], board: dict) -> None:
    width = float(board.get("width", 0.0))
    height = float(board.get("height", 0.0))

    if width <= 0 or height <= 0:
        return

    left = 0.0
    right = width
    bottom = 0.0
    top = height

    gerber_lines.append("G04 Board outline*")
    gerber_lines.append("D10*")
    gerber_lines.append(f"X{mm_to_coord(left)}Y{mm_to_coord(bottom)}D02*")
    gerber_lines.append(f"X{mm_to_coord(right)}Y{mm_to_coord(bottom)}D01*")
    gerber_lines.append(f"X{mm_to_coord(right)}Y{mm_to_coord(top)}D01*")
    gerber_lines.append(f"X{mm_to_coord(left)}Y{mm_to_coord(top)}D01*")
    gerber_lines.append(f"X{mm_to_coord(left)}Y{mm_to_coord(bottom)}D01*")


def generate_gerber(pcb_data: dict, output_dir: Path) -> None:
    # If gerber-writer is unavailable, fallback output is still generated by this script.
    # Installing gerber-writer enables future richer geometry emission.
    _ = gerber_writer

    output_dir.mkdir(parents=True, exist_ok=True)

    top_lines = [
        "G04 Top Copper*",
        "%FSLAX24Y24*%",
        "%MOMM*%",
        "%ADD10C,0.150*%",
        "%ADD11C,0.250*%",
        "%ADD12C,0.400*%",
        "%LPD*%",
    ]
    bottom_lines = [
        "G04 Bottom Copper*",
        "%FSLAX24Y24*%",
        "%MOMM*%",
        "%ADD10C,0.150*%",
        "%ADD11C,0.250*%",
        "%ADD12C,0.400*%",
        "%LPD*%",
    ]
    edge_cuts_lines = [
        "G04 Board Profile / Edge Cuts*",
        "%FSLAX24Y24*%",
        "%MOMM*%",
        "%ADD10C,0.100*%",
        "%LPD*%",
    ]
    drill_lines = [
        "M48",
        "METRIC,TZ",
        "T01C0.300",
        "%",
    ]
    silk_lines = [
        "G04 Silkscreen labels*",
        "%FSLAX24Y24*%",
        "%MOMM*%",
        "%LPD*%",
    ]

    components = pcb_data.get("components", [])
    traces = pcb_data.get("traces", [])
    board = pcb_data.get("board", {})
    origin = board.get("origin", {})
    origin_x = float(origin.get("x", 0.0))
    origin_y = float(origin.get("y", 0.0))

    for component in components:
        x = float(component.get("position", {}).get("x", 0.0))
        y = float(component.get("position", {}).get("y", 0.0))
        layer = component.get("layer", "top")
        designator = component.get("designator", component.get("id", "U?"))
        local_x, local_y = to_board_local(x, y, origin_x, origin_y)

        coord = f"X{mm_to_coord(local_x)}Y{mm_to_coord(local_y)}D03*"
        if layer == "bottom":
            bottom_lines.append(coord)
        else:
            top_lines.append(coord)

        silk_lines.append(f"G04 {designator} @ {local_x:.3f},{local_y:.3f}*")
        drill_lines.append(f"X{mm_to_coord(local_x)}Y{mm_to_coord(local_y)}")

    for trace in traces:
        layer = trace.get("layer", "top")
        width_mm = float(trace.get("widthMm", 0.25))
        points = trace.get("points", [])
        vias = trace.get("vias", [])

        if width_mm <= 0.18:
            aperture = "D10"
        elif width_mm <= 0.32:
            aperture = "D11"
        else:
            aperture = "D12"

        if layer == "bottom":
            append_trace(bottom_lines, points, aperture, origin_x, origin_y)
        else:
            append_trace(top_lines, points, aperture, origin_x, origin_y)

        for via in vias:
            vx = float(via.get("x", 0.0))
            vy = float(via.get("y", 0.0))
            local_vx, local_vy = to_board_local(vx, vy, origin_x, origin_y)
            drill_lines.append(f"X{mm_to_coord(local_vx)}Y{mm_to_coord(local_vy)}")

    append_board_outline(edge_cuts_lines, board)

    top_lines.append("M02*")
    bottom_lines.append("M02*")
    edge_cuts_lines.append("M02*")
    silk_lines.append("M02*")
    drill_lines.append("M30")

    write_stub_file(output_dir / "top_copper.gbr", top_lines)
    write_stub_file(output_dir / "bottom_copper.gbr", bottom_lines)
    write_stub_file(output_dir / "edge_cuts.gbr", edge_cuts_lines)
    write_stub_file(output_dir / "silkscreen_top.gbr", silk_lines)
    write_stub_file(output_dir / "drill.drl", drill_lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Gerber artifacts from flattened PCB JSON")
    parser.add_argument("--input", required=True, help="Input PCB JSON path")
    parser.add_argument("--output", required=True, help="Output directory")
    args = parser.parse_args()

    input_path = Path(args.input)
    output_dir = Path(args.output)

    pcb_data = json.loads(input_path.read_text(encoding="utf-8"))
    generate_gerber(pcb_data, output_dir)


if __name__ == "__main__":
    main()
