import JSZip from 'jszip';
import { execFile } from 'node:child_process';
import { promises as fs } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { promisify } from 'node:util';

import { FlattenedPcb, Position, Trace, Via } from '@/types/pcb';

const execFileAsync = promisify(execFile);

type ExecFileError = Error & {
  code?: string;
  stdout?: string;
  stderr?: string;
};

type LocalPoint = {
  x: number;
  y: number;
};

export type GerberExportOptions = {
  silkscreenStrokeMm?: number;
};

function clamp(value: number, low: number, high: number) {
  return Math.max(low, Math.min(high, value));
}

function toBoardLocal(point: Position, flattened: FlattenedPcb): LocalPoint {
  return {
    x: point.x - flattened.board.origin.x,
    y: point.y - flattened.board.origin.y,
  };
}

function formatApertureMm(value: number) {
  return value.toFixed(4);
}

function formatGerberCoord(value: number) {
  const scaled = Math.round(value * 10000);
  const abs = Math.abs(scaled).toString().padStart(7, '0');
  return `${scaled < 0 ? '-' : ''}${abs}`;
}

function gerberXY(point: LocalPoint) {
  return `X${formatGerberCoord(point.x)}Y${formatGerberCoord(point.y)}`;
}

function makeGerberHeader() {
  return [
    'G04 Generated by Modstract TS fallback exporter*',
    '%FSLAX34Y34*%',
    '%MOMM*%',
    'G01*',
  ];
}

function makeGerberFooter() {
  return ['M02*'];
}

function distributePinsAcrossSides(
  count: number,
  bodyWidth: number,
  bodyHeight: number
) {
  if (count <= 1) {
    return { left: 0, right: 1, top: 0, bottom: 0 };
  }

  if (count === 2) {
    return { left: 1, right: 1, top: 0, bottom: 0 };
  }

  if (count === 3) {
    return { left: 1, right: 1, top: 1, bottom: 0 };
  }

  const sideOrder: Array<'top' | 'right' | 'bottom' | 'left'> = [
    'top',
    'right',
    'bottom',
    'left',
  ];
  const sideLengths = {
    top: bodyWidth,
    bottom: bodyWidth,
    left: bodyHeight,
    right: bodyHeight,
  };
  const totalLength =
    sideLengths.top + sideLengths.right + sideLengths.bottom + sideLengths.left;

  const base = {
    top: Math.floor((count * sideLengths.top) / totalLength),
    right: Math.floor((count * sideLengths.right) / totalLength),
    bottom: Math.floor((count * sideLengths.bottom) / totalLength),
    left: Math.floor((count * sideLengths.left) / totalLength),
  };

  if (count >= 4) {
    sideOrder.forEach((side) => {
      if (base[side] === 0) {
        base[side] = 1;
      }
    });
  }

  let assigned = base.top + base.right + base.bottom + base.left;
  let remaining = count - assigned;

  const ranking = sideOrder
    .map((side) => ({
      side,
      frac: (count * sideLengths[side]) / totalLength - base[side],
    }))
    .sort((a, b) => b.frac - a.frac);

  let rankIndex = 0;
  while (remaining > 0) {
    const side = ranking[rankIndex % ranking.length].side;
    base[side] += 1;
    remaining -= 1;
    rankIndex += 1;
  }

  while (remaining < 0) {
    const candidates = sideOrder.filter((side) => base[side] > 1);
    if (candidates.length === 0) {
      break;
    }
    const side = candidates[rankIndex % candidates.length];
    base[side] -= 1;
    remaining += 1;
    rankIndex += 1;
  }

  assigned = base.top + base.right + base.bottom + base.left;
  if (assigned !== count) {
    base.right += count - assigned;
  }

  return base;
}

function createPadAnchors(
  pinIds: string[],
  bodyWidth: number,
  bodyHeight: number
) {
  const counts = distributePinsAcrossSides(
    pinIds.length,
    bodyWidth,
    bodyHeight
  );
  const sides: Array<'top' | 'right' | 'bottom' | 'left'> = [];

  Array.from({ length: counts.top }).forEach(() => sides.push('top'));
  Array.from({ length: counts.right }).forEach(() => sides.push('right'));
  Array.from({ length: counts.bottom }).forEach(() => sides.push('bottom'));
  Array.from({ length: counts.left }).forEach(() => sides.push('left'));

  if (sides.length === 0) {
    sides.push('right');
  }

  const bySide: Record<'top' | 'right' | 'bottom' | 'left', string[]> = {
    top: [],
    right: [],
    bottom: [],
    left: [],
  };

  pinIds.forEach((pinId, index) => {
    const side = sides[index % sides.length];
    bySide[side].push(pinId);
  });

  const anchors: Array<{ id: string; x: number; y: number }> = [];
  (['top', 'right', 'bottom', 'left'] as const).forEach((side) => {
    const sidePins = bySide[side];
    sidePins.forEach((pinId, index) => {
      const t = (index + 1) / (sidePins.length + 1);
      const x =
        side === 'left' ? 0 : side === 'right' ? bodyWidth : t * bodyWidth;
      const y =
        side === 'top' ? 0 : side === 'bottom' ? bodyHeight : t * bodyHeight;
      anchors.push({ id: pinId, x, y });
    });
  });

  return anchors;
}

function componentPadDiameterMm(bodyWidth: number, bodyHeight: number) {
  return clamp(Math.min(bodyWidth, bodyHeight) * 0.24, 0.35, 1.2);
}

function formatSquareApertureMm(sizeMm: number) {
  const formatted = formatApertureMm(sizeMm);
  return `${formatted}X${formatted}`;
}

function writeTraceSegments(
  lines: string[],
  trace: Trace,
  flattened: FlattenedPcb
) {
  if (trace.points.length < 2) {
    return;
  }

  const points = trace.points.map((point) => toBoardLocal(point, flattened));
  lines.push(`${gerberXY(points[0])}D02*`);
  points.slice(1).forEach((point) => {
    lines.push(`${gerberXY(point)}D01*`);
  });
}

function writeVias(
  topLines: string[],
  bottomLines: string[],
  drillBySize: Map<number, LocalPoint[]>,
  traces: Trace[],
  flattened: FlattenedPcb
) {
  const viaPads = new Set<number>();

  traces.forEach((trace) => {
    trace.vias.forEach((via: Via) => {
      viaPads.add(clamp(via.padMm || 0.6, 0.1, 8));
    });
  });

  const sortedPads = Array.from(viaPads).sort((a, b) => a - b);
  const apertureForPad = new Map<number, number>();
  let apertureIndex = 40;

  sortedPads.forEach((padMm) => {
    apertureForPad.set(padMm, apertureIndex);
    topLines.splice(4, 0, `%ADD${apertureIndex}C,${formatApertureMm(padMm)}*%`);
    bottomLines.splice(
      4,
      0,
      `%ADD${apertureIndex}C,${formatApertureMm(padMm)}*%`
    );
    apertureIndex += 1;
  });

  traces.forEach((trace) => {
    trace.vias.forEach((via: Via) => {
      const padMm = clamp(via.padMm || 0.6, 0.1, 8);
      const drillMm = clamp(via.drillMm || 0.3, 0.05, 8);
      const aperture = apertureForPad.get(padMm);
      const local = toBoardLocal({ x: via.x, y: via.y }, flattened);
      if (!aperture) {
        return;
      }

      topLines.push(`D${aperture}*`);
      topLines.push(`${gerberXY(local)}D03*`);
      bottomLines.push(`D${aperture}*`);
      bottomLines.push(`${gerberXY(local)}D03*`);

      const roundedDrill = Number(drillMm.toFixed(3));
      const current = drillBySize.get(roundedDrill) ?? [];
      current.push(local);
      drillBySize.set(roundedDrill, current);
    });
  });
}

function buildCopperGerbers(flattened: FlattenedPcb) {
  const topLines = makeGerberHeader();
  const bottomLines = makeGerberHeader();

  const traceWidths = new Set<number>();
  flattened.traces.forEach((trace) => {
    traceWidths.add(clamp(trace.widthMm || 0.25, 0.05, 5));
  });

  const sortedTraceWidths = Array.from(traceWidths).sort((a, b) => a - b);
  const apertureByTraceWidth = new Map<number, number>();
  let apertureIndex = 10;
  sortedTraceWidths.forEach((width) => {
    apertureByTraceWidth.set(width, apertureIndex);
    topLines.push(`%ADD${apertureIndex}C,${formatApertureMm(width)}*%`);
    bottomLines.push(`%ADD${apertureIndex}C,${formatApertureMm(width)}*%`);
    apertureIndex += 1;
  });

  const componentPadDiameterBySize = new Map<number, number>();
  flattened.components.forEach((component) => {
    const bodyWidth = Math.max(0.1, component.bounds.width || 2);
    const bodyHeight = Math.max(0.1, component.bounds.height || 1.25);
    const padDiameter = componentPadDiameterMm(bodyWidth, bodyHeight);
    if (!componentPadDiameterBySize.has(padDiameter)) {
      componentPadDiameterBySize.set(padDiameter, apertureIndex);
      topLines.push(
        `%ADD${apertureIndex}R,${formatSquareApertureMm(padDiameter)}*%`
      );
      bottomLines.push(
        `%ADD${apertureIndex}R,${formatSquareApertureMm(padDiameter)}*%`
      );
      apertureIndex += 1;
    }
  });

  flattened.components.forEach((component) => {
    const bodyWidth = Math.max(0.1, component.bounds.width || 2);
    const bodyHeight = Math.max(0.1, component.bounds.height || 1.25);
    const pinIds = component.pins.map((pin) => pin.id).filter(Boolean);
    const anchors = createPadAnchors(
      pinIds.length > 0 ? pinIds : ['1'],
      bodyWidth,
      bodyHeight
    );
    const padDiameter = componentPadDiameterMm(bodyWidth, bodyHeight);
    const aperture = componentPadDiameterBySize.get(padDiameter);
    if (!aperture) {
      return;
    }

    const targetLines = component.layer === 'bottom' ? bottomLines : topLines;
    targetLines.push(`D${aperture}*`);
    anchors.forEach((anchor) => {
      const global = {
        x: component.position.x + (anchor.x - bodyWidth / 2),
        y: component.position.y + (anchor.y - bodyHeight / 2),
      };
      const local = toBoardLocal(global, flattened);
      targetLines.push(`${gerberXY(local)}D03*`);
    });
  });

  flattened.traces.forEach((trace) => {
    const width = clamp(trace.widthMm || 0.25, 0.05, 5);
    const aperture = apertureByTraceWidth.get(width);
    if (!aperture) {
      return;
    }

    const targetLines = trace.layer === 'bottom' ? bottomLines : topLines;
    targetLines.push(`D${aperture}*`);
    writeTraceSegments(targetLines, trace, flattened);
  });

  const drillBySize = new Map<number, LocalPoint[]>();
  writeVias(topLines, bottomLines, drillBySize, flattened.traces, flattened);

  topLines.push(...makeGerberFooter());
  bottomLines.push(...makeGerberFooter());

  return {
    top: `${topLines.join('\n')}\n`,
    bottom: `${bottomLines.join('\n')}\n`,
    drills: drillBySize,
  };
}

function buildEdgeCutsGerber(flattened: FlattenedPcb) {
  const width = Math.max(1, flattened.board.width || 100);
  const height = Math.max(1, flattened.board.height || 80);

  const lines = makeGerberHeader();
  lines.push('%ADD10C,0.1500*%');
  lines.push('D10*');
  lines.push(`${gerberXY({ x: 0, y: 0 })}D02*`);
  lines.push(`${gerberXY({ x: width, y: 0 })}D01*`);
  lines.push(`${gerberXY({ x: width, y: height })}D01*`);
  lines.push(`${gerberXY({ x: 0, y: height })}D01*`);
  lines.push(`${gerberXY({ x: 0, y: 0 })}D01*`);
  lines.push(...makeGerberFooter());

  return `${lines.join('\n')}\n`;
}

function buildSilkscreenGerber() {
  const lines = makeGerberHeader();
  lines.push(...makeGerberFooter());
  return `${lines.join('\n')}\n`;
}

function formatExcellonCoord(value: number) {
  return (Math.round(value * 1000) / 1000).toFixed(3);
}

function buildDrillFile(drills: Map<number, LocalPoint[]>) {
  const sortedTools = Array.from(drills.keys()).sort((a, b) => a - b);
  if (sortedTools.length === 0) {
    return 'M48\nMETRIC,TZ\n%\nM30\n';
  }

  const lines = ['M48', 'METRIC,TZ'];
  sortedTools.forEach((diameter, index) => {
    const tool = String(index + 1).padStart(2, '0');
    lines.push(`T${tool}C${diameter.toFixed(3)}`);
  });
  lines.push('%');

  sortedTools.forEach((diameter, index) => {
    const tool = String(index + 1).padStart(2, '0');
    lines.push(`T${tool}`);
    const points = drills.get(diameter) ?? [];
    points.forEach((point) => {
      lines.push(
        `X${formatExcellonCoord(point.x)}Y${formatExcellonCoord(point.y)}`
      );
    });
  });

  lines.push('M30');
  return `${lines.join('\n')}\n`;
}

async function runTypeScriptFallback(
  flattened: FlattenedPcb,
  outputDir: string
) {
  const { top, bottom, drills } = buildCopperGerbers(flattened);
  await Promise.all([
    fs.writeFile(path.join(outputDir, 'top_copper.gbr'), top, 'utf8'),
    fs.writeFile(path.join(outputDir, 'bottom_copper.gbr'), bottom, 'utf8'),
    fs.writeFile(
      path.join(outputDir, 'edge_cuts.gbr'),
      buildEdgeCutsGerber(flattened),
      'utf8'
    ),
    fs.writeFile(
      path.join(outputDir, 'silkscreen_top.gbr'),
      buildSilkscreenGerber(),
      'utf8'
    ),
    fs.writeFile(
      path.join(outputDir, 'silkscreen_bottom.gbr'),
      buildSilkscreenGerber(),
      'utf8'
    ),
    fs.writeFile(
      path.join(outputDir, 'drill.drl'),
      buildDrillFile(drills),
      'utf8'
    ),
  ]);
}

async function runPython(
  scriptPath: string,
  inputPath: string,
  outputDir: string,
  options?: GerberExportOptions
) {
  const pythonCandidates = [
    process.env.PYTHON,
    process.env.PYTHON_PATH,
    path.join(process.cwd(), '.venv', 'bin', 'python'),
    path.join(process.cwd(), '.venv', 'bin', 'python3'),
    path.join(process.cwd(), '.venv', 'Scripts', 'python.exe'),
    '/var/lang/bin/python3.12',
    '/var/lang/bin/python3.11',
    '/var/lang/bin/python3.10',
    '/usr/local/bin/python3',
    '/usr/bin/python3',
    '/opt/homebrew/bin/python3',
    'python3',
    'python',
  ].filter((candidate): candidate is string => Boolean(candidate));
  let lastError: ExecFileError | undefined;

  const args = [scriptPath, '--input', inputPath, '--output', outputDir];
  if (typeof options?.silkscreenStrokeMm === 'number') {
    args.push('--silk-stroke-mm', String(options.silkscreenStrokeMm));
  }

  for (const command of pythonCandidates) {
    try {
      await execFileAsync(command, args);
      return;
    } catch (error) {
      const execError = error as ExecFileError;
      lastError = execError;

      // Keep searching only if the executable does not exist.
      if (execError.code !== 'ENOENT') {
        break;
      }
    }
  }

  if (lastError instanceof Error) {
    const parts = [
      `Unable to run Python Gerber generator at ${scriptPath}.`,
      `Cause: ${lastError.message}`,
      `Tried Python candidates: ${pythonCandidates.join(', ')}`,
      lastError.stderr ? `stderr: ${lastError.stderr.trim()}` : '',
      lastError.stdout ? `stdout: ${lastError.stdout.trim()}` : '',
    ].filter(Boolean);

    const wrappedError = new Error(parts.join(' | ')) as ExecFileError;
    wrappedError.code = lastError.code;
    throw wrappedError;
  }

  throw new Error('Unable to run Python Gerber generator.');
}

export async function generateGerberZip(
  flattened: FlattenedPcb,
  options?: GerberExportOptions
): Promise<Buffer> {
  const workspaceRoot = process.cwd();
  const scriptPath = path.join(
    workspaceRoot,
    'scripts',
    'pcb',
    'generate_gerber.py'
  );
  const tmpRoot = await fs.mkdtemp(path.join(os.tmpdir(), 'pcb-export-'));
  const inputPath = path.join(tmpRoot, 'pcb.json');
  const outputDir = path.join(tmpRoot, 'gerber');

  try {
    await fs.mkdir(outputDir, { recursive: true });
    await fs.writeFile(inputPath, JSON.stringify(flattened, null, 2), 'utf8');

    const preferTypeScriptFallback =
      process.env.PREFER_TS_GERBER_EXPORT === '1';
    if (preferTypeScriptFallback) {
      await runTypeScriptFallback(flattened, outputDir);
    } else {
      try {
        await fs.access(scriptPath);
        await runPython(scriptPath, inputPath, outputDir, options);
      } catch (error) {
        const execError = error as ExecFileError;
        if (execError.code !== 'ENOENT') {
          throw error;
        }

        await runTypeScriptFallback(flattened, outputDir);
      }
    }

    const zip = new JSZip();
    const entries = await fs.readdir(outputDir, { withFileTypes: true });

    await Promise.all(
      entries
        .filter((entry) => entry.isFile())
        .map(async (entry) => {
          const fullPath = path.join(outputDir, entry.name);
          const content = await fs.readFile(fullPath);
          zip.file(entry.name, content);
        })
    );

    return zip.generateAsync({ type: 'nodebuffer' });
  } finally {
    await fs.rm(tmpRoot, { recursive: true, force: true });
  }
}
